### ISSUE TITLE
AMarchingChunk::Generate2DHeightMap strange terrain

### ISSUE THREAD

**Issue by shrEAX8** [BLaZeKiLL/UE5VoxelTutorial#1]
Using Generate2DHeightMap instead of Generate3DHeightMap leads to strange terrain.

The Xpos/Ypos calculation should probably changed from:
`const float Xpos = x * Position.X;`
`const float Ypos = y * Position.Y;`
To:
`const float Xpos = x + Position.X;`
`const float Ypos = y + Position.Y;`

**Comment by BLaZeKiLL** [comment]
right it needs to be
```
const float Xpos = x * 100 + Position.X;
const float Ypos = y * 100 + Position.Y;
```
To count for unreal engine unit scaling
