### ISSUE TITLE
Crash trying to implement Greedy Meshing in UE4 (Array index out of bounds)

### ISSUE THREAD

**Issue by Ayliroe** [BLaZeKiLL/UE5VoxelTutorial#13]
Hello!
THANK YOU FOR YOUR TUTORIAL, it's really amazing.

I'm having an issue trying to implement the greedy meshing shown in your episode 4. I've copied completely identically the code shown in the video (not the one in the UE5 github), with the necessary modifications to use the noise plugin. There's no UE4 greedy example provided unfortunately!

It generates the chunk normally but crashes when the size is set beyond 16 or with multiple chunks being spawned, with an error "Array index out of bounds". It's always from ChunkGreedy.cpp, but the lines often changes (24, 36, 94, 143), usually corresponding to "if (Mask[N].Normal != 0) {" or "Mesh->CreateMeshSection". The array size also changes, ex. on the provided crash "4096 from an array of size 4096", sometimes 512, etc. Maybe related to how TArrays work in UE4 versus UE5?

Here's the crash and sources I'm using:
[Crash.log](https://github.com/BLaZeKiLL/UE5VoxelTutorial/files/8874026/Crash.log)
[Private.zip](https://github.com/BLaZeKiLL/UE5VoxelTutorial/files/8874030/Private.zip)
(Using UE 4.25 in a clean C++ project with nothing else)

It does greedy meshing exactly as expected otherwise.

**Comment by BLaZeKiLL** [comment]
Are you trying a non-cubic (same value for all components) that may cause issues, tough ideally it should work, also looking at you code everything seems fine. debugging and checking the state of other variables when the error is thrown would be you best bet. when I first implemented this algorithm in unity I tried it out for All sort of crazy chunk sizes.

[unity source code](https://github.com/BLaZeKiLL/Detris/blob/main/Assets/Scripts/Voxel/Mesh/MeshBuilder.cs)

the above implementation is tested of various sizes and works. try to compare with this one maybe I am handling some boundary cases. I'll also go over it once and update if required

I started this project on UE4 and I don't think so there is any code change required between UE4 and UE5 as we barely use any unreal specific API.

**Comment by Ayliroe** [comment]
Found the crash!

From using the VS debugger:
- Breakpoint on the line that fill the Blocks array ( Blocks[GetBlockIndex(x, y, z)] = EBlock::Stone; ):
It starts filling in, up until reaching Position (0,0,4), which equals to index 4096, where it breaks. Same again at (0,0,5) equalling 5122, and so on.
- Breakpoint on the line "Blocks.SetNum(Size.X * Size.Y * Size.Z);":
The Size integers always remain at 16, even if set at 32 in editor. Meaning that SetNum will always return 4096, not 32768 as expected, and and a result breaking everything else.
![UE4Editor_20220612_220827_713](https://user-images.githubusercontent.com/106384472/173252251-52a9b7cf-1775-47ac-b4e4-114170db50e8.jpg)

Moving the SetNum line into BeginPlay fixes the crash.

I'm still getting some wrong triangles on any scale above 16, so there might be some "hardcoded" behavior remaining:
![UE4Editor_20220612_220827_713](https://user-images.githubusercontent.com/106384472/173252251-52a9b7cf-1775-47ac-b4e4-114170db50e8.jpg)

**Comment by BLaZeKiLL** [comment]
Makes sense, constructors are called before the unreal runtime so blueprint values won't be available there, will need to refactor this. Thanks 👍

**Comment by Ayliroe** [comment]
Just closing this, since both issues (the SetNum being in the wrong function and the broken faces at certain scales) are completely absent from your later implementations on GitHub anyway. Only really pertinent to people following straight from the video tutorial.
Cheers!
