### ISSUE TITLE
Width is Actually Height and Height is Width

### ISSUE THREAD

**Issue by pedrohugorm** [BLaZeKiLL/UE5VoxelTutorial#15]
I was setting up some UVs to do something other than terrain with the greedy mesh code and I noticed the Width and Height are reversed.
By changing Width -> Height and Height -> Width the UVs work as Expected.

**Comment by BLaZeKiLL** [comment]
I hadn't tested out the UV's yet so thanks for the heads up. was going to start implementing texture arrays this weekend

**Comment by BLaZeKiLL** [comment]
```cpp
if (Normal.X == 1 || Normal.X == -1)
{
    MeshData.UV0.Append({
        FVector2D(Width, Height),
        FVector2D(0, Height),
        FVector2D(Width, 0),
        FVector2D(0, 0),
    });
}
else
{
    MeshData.UV0.Append({
        FVector2D(Height, Width),
        FVector2D(Height, 0),
        FVector2D(0, Width),
        FVector2D(0, 0),
    });
}
```

So this code gave me the correct result, I think UV alignment is axis dependant. There may be a better/simpler way to do this.
