### ISSUE TITLE
Materials are rotated on some faces.

### ISSUE THREAD

**Issue by jmancoder** [BLaZeKiLL/UE5VoxelTutorial#6]
This only occurs in the GreedyMesh chunk type. The applied material is rotated by 90 degrees on some faces. I have included a screenshot of both a Greedy Chunk and a Naive Chunk.
![Greedy Chunk](https://user-images.githubusercontent.com/93668101/140170927-6b3f0e69-c1d7-41ab-96bf-b157cc9a7b2f.png)
![Naive Chunk](https://user-images.githubusercontent.com/93668101/140170932-391b3ff9-90f9-4766-9730-c8928f2abf76.png)

**Comment by BLaZeKiLL** [comment]
looks like a UV ordering issue, I'll check it

**Comment by jmancoder** [comment]
Thank you. The problem may actually lie with the triangles. They appear to have rather inconsistent angles in Greedy Meshing.

**Comment by jmancoder** [comment]
I fixed this by making my materials World Aligned.

**Comment by BLaZeKiLL** [comment]
Did you face scaling issues in greedy meshing ? You can also raise a PR for the fix I'll be happy to merge it

**Comment by jmancoder** [comment]
> Did you face scaling issues in greedy meshing ? You can also raise a PR for the fix I'll be happy to merge it

Sorry, but what do you mean by scaling issues? I just added a World Aligned Texture node to my materials; no code was changed.

**Comment by BLaZeKiLL** [comment]
> > Did you face scaling issues in greedy meshing ? You can also raise a PR for the fix I'll be happy to merge it
> 
> Sorry, but what do you mean by scaling issues? I just added a World Aligned Texture node to my materials; no code was changed.

Since greedy meshing creates faces of different sized I thought the textures would be stretched on them unless some custom mapping logic was involved that take into consideration the width and height of the face

**Comment by BLaZeKiLL** [comment]
@jmancoder you can take a look at #15 that should be the proper fix
